//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintEngine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Metadatas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Metadatas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintEngine.Resources.Metadatas", typeof(Metadatas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;Mappings&quot;: [
        ///  { &quot;EOSAGOPOLICY&quot;: &quot;OSAGOPOLICY&quot; }
        ///  
        /// ],
        /// &quot;Values&quot;: {
        ///   &quot;OSAGOPOLICY&quot;: {
        ///    &quot;DocType&quot;: &quot;DocType&quot;,
        ///    &quot;ContractConclusionDate&quot;: &quot;ContractConclusionDate&quot;,
        ///    &quot;ContractDate&quot;: &quot;ContractDate&quot;,
        ///    &quot;ContractEnd&quot;: &quot;ContractEnd&quot;,
        ///    &quot;ContractStart&quot;: &quot;ContractStart&quot;,
        ///    &quot;CurrentDocumentNumber&quot;: &quot;CurrentDocumentNumber&quot;,
        ///    &quot;CurrentDocumentSeries&quot;: &quot;CurrentDocumentSeries&quot;,
        ///    &quot;HasTrailer&quot;: &quot;HasTrailer&quot;,
        ///    &quot;InsurancePremium&quot;: &quot;InsurancePremium&quot;,
        ///    &quot;Insurant&quot;: &quot;Insurant&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MappingMetadata {
            get {
                return ResourceManager.GetString("MappingMetadata", resourceCulture);
            }
        }
    }
}
